### ISSUE TITLE
Pluralized references broken

### ISSUE THREAD

**Issue by shysteph** [JakeWheat/sql-overview#5]
A reference with a "s" at the end doesn't get turned into a link.  For example "this <reference> would work but <reference>s like this don't".

See: https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_13_4_sql_procedure_statement

**Comment by JakeWheat** [comment]
I think the issue is that the processor doesn't attempt to change any references in Function sections into links, e.g. see https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#_20_19_dynamic_open_statement
It's only adding links to the grammar sections (called 'Format' in the spec).

**Comment by JakeWheat** [comment]
I think there isn't an issue here, but please reopen and comment if you think there is
